### ISSUE TITLE
Frontend: Authorization

### ISSUE THREAD

**Issue by plplmax** [plplmax/unicorn-team-chat#4]
- [x] #6
- [x] #7
- [x] #8
- [x] #25
- [x] #9
- [x] #10
- [x] #11

**Comment by 0pdd** [comment]
@plplmax 3 puzzles [#41](https://github.com/plplmax/unicorn-team-chat/issues/41), [#42](https://github.com/plplmax/unicorn-team-chat/issues/42), [#43](https://github.com/plplmax/unicorn-team-chat/issues/43) are still not solved.

**Comment by 0pdd** [comment]
@plplmax the puzzle [#41](https://github.com/plplmax/unicorn-team-chat/issues/41) is still not solved; solved: [#42](https://github.com/plplmax/unicorn-team-chat/issues/42), [#43](https://github.com/plplmax/unicorn-team-chat/issues/43).

**Comment by 0pdd** [comment]
@plplmax all 3 puzzles are solved here: [#41](https://github.com/plplmax/unicorn-team-chat/issues/41), [#42](https://github.com/plplmax/unicorn-team-chat/issues/42), [#43](https://github.com/plplmax/unicorn-team-chat/issues/43).
