### ISSUE TITLE
Feature: Messenger

### ISSUE THREAD

**Issue by plplmax** [plplmax/unicorn-team-chat#45]
- [x] #46
- [x] #47
- [x] #48
- [x] #49

<img width="464" alt="Screenshot 2023-04-22 at 14 53 33" src="https://user-images.githubusercontent.com/50287455/233783177-8c93efb0-0c60-44cc-b752-45ceeb0f0484.png">

**Comment by 0pdd** [comment]
@plplmax 2 puzzles [#51](https://github.com/plplmax/unicorn-team-chat/issues/51), [#52](https://github.com/plplmax/unicorn-team-chat/issues/52) are still not solved.

**Comment by 0pdd** [comment]
@plplmax the puzzle [#52](https://github.com/plplmax/unicorn-team-chat/issues/52) is still not solved; solved: [#51](https://github.com/plplmax/unicorn-team-chat/issues/51).
